char *LOGO[] = {
	"                                     ",
    "                 o                   ",
    "                ooo                  ",
    "               ooooo                 ",
    "              ooooooo                ",
    "             ooooooooo               ",
    "            ooooo ooooo              ",
    "           ooooo   ooooo             ",
    "          ooooo     ooooo            ",
    "         ooooo       ooooo           ",
    "        ooooo         ooooo          ",
    "       ooooo           ooooo         ",
    "      ooooo             ooooo        ",
    "     ooooo               ooooo       ",
    "    ooooo       ooooooooooooooo      ",
   	"   ooooo           ooooooooooooo     ",
  	"  ooooo                oooooooooo    ",
 	" ooooo                     ooooooo   ",
	"ooooo                         ooooo  "
};
