char *LOGO[] = {
	"                                        ",
    "                   oo:                  ",
    "                  yoo/                  ",
    "                 yooooo                 ",
    "                yooooooo                ",
    "               yooooooooo               ",
    "             .yooooooooooo              ",
    "            .oooooooooooooo             ",
    "           .ooooooarcooooooo            ",
    "          .oooooooo-ooooooooo           ",
    "         .oooooooo-  ooooooooo          ",
    "        :oooooooo.    :oooooooo         ",
    "       :oooooooo.      :oooooooo        ",
    "      :ooarcooo         .oooarcoo       ",
    "     :oooooooy           .oooooooo      ",
    "    :oooooooo   ooooooooooooooooooo     ",
   	"   :oooooooo      .-oooooooooooooooo    ",
  	"  oooooooo-            -oooooooooooo.   ",
 	" oooooooo-                 -ooooooooo.  ",
	"oooooooo.                    -oooooooo  "
};
